name: first workflow

on: 
  # workflow_dispatch:
  #   inputs:
  #     versionName:
  #       description: "this version name for github workflow"
  #       required: true

  push:
    branches:
      - "main"

jobs:
  first_workflow_job:
    name: first jobs
    runs-on: ubuntu-latest
    steps:
      - name: before checkout action 
        if: GITHUB_REF == 'refs/heads/feature'
        run: ls 
        shell: bash 

      - name: checkout action
        uses: actions/checkout@v3

      - name: after checkout action
        run: ls     


